# -*- coding: utf-8 -*-
"""Opencv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8sp-R3DiCYTtz0XnomjYSbjeQ2zMCJC
"""

!pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('bmw.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('car.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('tiger.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)